### PR TITLE
Add  head and maintenance node ansible roles doc

### PR DESCRIPTION
**Pull request by sanjaysrikakulam**
Docs showing which role should be installed where. All roles are linked to their respective repos/folders/Ansible galaxy.

_If time permits I will go through each and every role listed here and try to add a brief description._

### CODE REVIEW

**Comment by bgruening** [comment]
I like the idea and the list, thanks @sanjaysrikakulam! Do you want to merge that or keep it open and work on it?

**Comment by sanjaysrikakulam** [comment]
I have converted this to a draft. I will try and spend some more time on it.

**Comment by mira-miracoli** [comment]
shall I delete my [roles without repos](https://github.com/usegalaxy-eu/operations/blob/main/roles-without-repos.md), then?

**Comment by sanjaysrikakulam** [comment]
> shall I delete my [roles without repos](https://github.com/usegalaxy-eu/operations/blob/main/roles-without-repos.md), then?

No, please keep it until I add documentation (descriptions). I will merge yours with mine.

**Comment by sanjaysrikakulam** [comment]
Role descriptions are added as part of this PR https://github.com/usegalaxy-eu/operations/pull/22

So merging this PR.

**Pull request merged**
